[package]
name = "openssl-sys"
version = "0.1.1"
edition = "2021"
links = "openssl"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
anyhow = "1.0.65"
